version: 1
services:
  - type: web
    name: node-server-project
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    autoDeploy: true
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: CLIENT_URL
        value: your_client_url_here